version: ~> 1.0

import:
  - silverstripe/silverstripe-travis-shared:config/provision/self.yml

env:
  global:
    - PHPUNIT_TEST=1

jobs:
  fast_finish: true
  include:
    - php: 7.1
      env:
        - COMPOSER_INSTALL_ARG=--prefer-lowest
    - php: 7.3
      env:
        - PHPCS_TEST=1
    - php: 7.4
      env:
    - php: nightly
      env:
        - COMPOSER_INSTALL_ARG=--ignore-platform-reqs
