language: php

dist: trusty

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  include:
    - php: 7.1
      env:
       - COMPOSER_SELFUPDATE_ARG=--1
       - COMPOSER_ARG=--prefer-lowest
    - php: 7.3
      env:
       - COMPOSER_SELFUPDATE_ARG=--1
    - php: 7.4
      env:
       - COMPOSER_SELFUPDATE_ARG=--preview
    - php: nightly
      env:
       - COMPOSER_ARG=--ignore-platform-reqs
       - COMPOSER_SELFUPDATE_ARG=--preview

fast_finish: true

before_script:
  - phpenv rehash
  - export PATH=~/.composer/vendor/bin:$PATH
  - composer self-update $COMPOSER_SELFUPDATE_ARG
  - composer validate
  - composer update --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile $COMPOSER_ARG

script:
  - vendor/bin/phpunit
  - composer run-script lint
